# Собираем правильный JDBC URL из отдельных переменных Vercel
spring.datasource.url=jdbc:postgresql://${ep-wandering-hat-aq9ic5lq-pooler.c-8.us-east-1.aws.neon.tech}:5432/${neondb}?sslmode=require
spring.datasource.username=${neondb_owner}
spring.datasource.password=${npg_aH2juEO0cBZI}

# Явно указываем драйвер и диалект для PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Чтобы Hibernate создал таблицы при первом запуске
spring.jpa.hibernate.ddl-auto=update