spring.datasource.url=jdbc:h2:mem:openpathdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
POSTGRES_URL=postgresql://neondb_owner:npg_aH2juEO0cBZI@ep-wandering-hat-aq9ic5lq-pooler.c-8.us-east-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require